EmployeeManagementSys/Controllers/EmpFamilyDetAdvnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmployeeManagementSys.DAL.Data;
using EmployeeManagementSys.DAL.Data.Model;
using EmployeeManagementSys.Services.Services;

namespace EmployeeManagementSys.Controllers
{
    public class EmpFamilyDetAdvnsController : Controller
    {
        private readonly EmployeeManagementDbContext _context;
        private readonly IEmpFamDetAdvnService _empFamDetAdvnService;

        public EmpFamilyDetAdvnsController(EmployeeManagementDbContext context, IEmpFamDetAdvnService empFamDetAdvnService)
        {
            _context = context;
            _empFamDetAdvnService = empFamDetAdvnService;
        }

        // GET: EmpFamilyDetAdvns
        public async Task<ActionResult> Index(string searchBy, string Search, int pageNumber = 1)
        {
            ViewData["JoinTables"] = await _empFamDetAdvnService.JoinTables();
            var results = await _empFamDetAdvnService.GetAllEmployee();
            
            //ViewData["average"] =  await _empFamDetAdvnService.GetAverage();
            if (Search == null)
            {
                return View(await PaginatedList<EmpFamilyDetAdvn>.CreateAsync(results, pageNumber, 3));
            }
            if(searchBy == "Name")
            {
                var data = results.Where
                    (e => e.EmployeeAdvn.FirstName.ToLower().Contains(Search.ToLower()))
                    .ToList();
                return View(await PaginatedList<EmpFamilyDetAdvn>.CreateAsync
                            (data, pageNumber, 3));
            }
            else
            {
                var data = results.Where
                  (e => e.Address.ToLower().Contains(Search.ToLower()))
                  .ToList();
                return View(await PaginatedList<EmpFamilyDetAdvn>.CreateAsync
                            (data, pageNumber, 3));
            }

        }

        // GET: EmpFamilyDetAdvns/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var EmpFamDetail = await _empFamDetAdvnService.GetEmpFamDetailsById(id);
           
            if (EmpFamDetail == null)
                
            {
                return NotFound();
            }

            return View(EmpFamDetail);
        }

        //GET: EmpFamilyDetAdvns/Create
        public IActionResult Create()
        {
            ViewData["EmployeeId"] = new SelectList(_context.EmployeeAdvn, "EmployeeId", "FirstName");
            return View();
        }

        // POST: EmpFamilyDetAdvns/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EmployeeId,Email,Salary,Address,Role,MemberName," +
            "MemberRelation,ContactNumber,CreatedOn,UpdatedOn")] EmpFamilyDetAdvn empFamilyDetAdvn)
        {
            if (ModelState.IsValid)
            {
                bool result = await _empFamDetAdvnService.CreateEmployee(empFamilyDetAdvn);
                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["EmployeeId"] = new SelectList(_context.EmployeeAdvn, "EmployeeId", "FirstName", empFamilyDetAdvn.EmployeeId);
            return View(empFamilyDetAdvn);
        }

        // GET: EmpFamilyDetAdvns/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empFamilyDetAdvn = await _empFamDetAdvnService.GetEmpFamDetailsById(id);
            if (empFamilyDetAdvn == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(_context.EmployeeAdvn, "EmployeeId", "FirstName", empFamilyDetAdvn.EmployeeId);
         
            return View(empFamilyDetAdvn);
        }

        // POST: EmpFamilyDetAdvns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EmployeeId,Email,Salary,Address,Role," +
            "MemberName,MemberRelation,ContactNumber,CreatedOn,UpdatedOn")] EmpFamilyDetAdvn empFamilyDetAdvn)
        {
            if (id != empFamilyDetAdvn.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _empFamDetAdvnService.UpdateEmployee(empFamilyDetAdvn);
                   
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpFamilyDetAdvnExists(empFamilyDetAdvn.EmployeeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.EmployeeAdvn, "EmployeeId", "FirstName", empFamilyDetAdvn.EmployeeId);
            return View(empFamilyDetAdvn);
        }

        // GET: EmpFamilyDetAdvns/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)

            {
                return NotFound();
            }

            var empFamilyDetAdvn = await _empFamDetAdvnService.GetEmpFamDetailsById(id);  
            if (empFamilyDetAdvn == null)
            {
                return NotFound();
            }

            return View(empFamilyDetAdvn);
        }

        // POST: EmpFamilyDetAdvns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empFamilyDetAdvn = await _context.EmpFamilyDetAdvn.FindAsync(id);
            _context.EmpFamilyDetAdvn.Remove(empFamilyDetAdvn);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpFamilyDetAdvnExists(int id)
        {
            return _empFamDetAdvnService.EmpFamilyDetAdvnExists(id);
        }


    }
}

EmployeeManagementSys/Views/EmpFamilyDetAdvns/Create.cshtml
@model EmployeeManagementSys.DAL.Data.Model.EmpFamilyDetAdvn; 

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>EmpFamilyDetAdvn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
            </div>
           
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberName" class="control-label"></label>
                <input asp-for="MemberName" class="form-control" />
                <span asp-validation-for="MemberName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberRelation" class="control-label"></label>
                <input asp-for="MemberRelation" class="form-control" />
                <span asp-validation-for="MemberRelation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNumber" class="control-label"></label>
                <input asp-for="ContactNumber" class="form-control" />
                <span asp-validation-for="ContactNumber" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" />
                <span asp-validation-for="CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedOn" class="control-label"></label>
                <input asp-for="UpdatedOn" class="form-control" />
                <span asp-validation-for="UpdatedOn" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EmployeeManagementSys/Views/EmpFamilyDetAdvns/Delete.cshtml
@model EmployeeManagementSys.DAL.Data.Model.EmpFamilyDetAdvn

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EmpFamilyDetAdvn</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MemberName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MemberName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MemberRelation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MemberRelation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeAdvn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeAdvn.FirstName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EmployeeManagementSys/Views/EmpFamilyDetAdvns/Details.cshtml
@model EmployeeManagementSys.DAL.Data.Model.EmpFamilyDetAdvn;

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>EmpFamilyDetAdvn</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MemberName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MemberName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MemberRelation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MemberRelation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedOn)
        </dd>
       
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EmployeeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EmployeeManagementSys/Views/EmpFamilyDetAdvns/Edit.cshtml
@model EmployeeManagementSys.DAL.Data.Model.EmpFamilyDetAdvn;

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>EmpFamilyDetAdvn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EmployeeId" />
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberName" class="control-label"></label>
                <input asp-for="MemberName" class="form-control" />
                <span asp-validation-for="MemberName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberRelation" class="control-label"></label>
                <input asp-for="MemberRelation" class="form-control" />
                <span asp-validation-for="MemberRelation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNumber" class="control-label"></label>
                <input asp-for="ContactNumber" class="form-control" />
                <span asp-validation-for="ContactNumber" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" />
                <span asp-validation-for="CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedOn" class="control-label"></label>
                <input asp-for="UpdatedOn" class="form-control" />
                <span asp-validation-for="UpdatedOn" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EmployeeManagementSys/Views/EmpFamilyDetAdvns/Index.cshtml
@using EmployeeManagementSys.Services.ViewModel;
@model PaginatedList<EmployeeManagementSys.DAL.Data.Model.EmpFamilyDetAdvn>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" />*@
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap4.min.css" />
<h1>Index</h1>
@*<p>
        Average Salary:
        @ViewData["Average"].ToString()
    </p>*@

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    @using (Html.BeginForm("Index", "EmpFamilyDetAdvns", FormMethod.Get))
    {
        <b>Search By:</b> @Html.RadioButton("searchBy", "Name", true) <text>Name</text>
        @Html.RadioButton("searchBy", "Address") <text>Address</text> <br />
        @Html.TextBox("Search") <input type="submit" value="Search" />
    }
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Email
            </th>
            <th>
                Salary
            </th>
            <th>
                Address
            </th>
            <th>
                Role
            </th>
            <th>
                MemberName
            </th>
            <th>
                MemberRelation
            </th>
            <th>
                ContactNumber
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedOn)
                </th>*@
            <th>
                Employee Name
            </th>

        </tr>
    </thead>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="4">No rows match search criteria</td>
        </tr>
    }
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Role)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberRelation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactNumber)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdatedOn)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.EmployeeAdvn.FirstName)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.PreviousPage ? "disabled" : "";
    var nextDisabled = !Model.NextPage ? "disabled" : "";

}

<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex -1)"
   class="btn btn-default @prevDisabled">Previous</a>

<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex +1)"
   class="btn btn-default @nextDisabled">Next</a>



@{
    var Data = ViewData["JoinTables"] as List<vwJoinData>;
}
<table id="Join" class="table">
    <thead>
        <tr>
            <th>
                FirstName
            </th>
            <th>
                LastName
            </th>
            <th>
                Email
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Data)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.firstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.lastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script src="~/js/jquery-3.5.1.js"></script>
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="~/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#Join').DataTable();
        });
    </script>
}